name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Restore Infra.Http.Api
      run: dotnet restore ./Infra.Http.Api.slnx

    - name: Build Infra.Http.Api
      run: dotnet build ./Infra.Http.Api.slnx --no-restore -c Release

    - name: Test Infra.Http.Api
      run: dotnet test ./Infra.Http.Api.slnx --no-restore -c Release

    - name: Pack Infra.Http.Api
      run: dotnet pack ./Infra.Http.Api.slnx --no-build -o ~/nuget -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s https://api.nuget.org/v3/index.json
        -k ${{ secrets.NUGET_SECRET }}
        --skip-duplicate
